### PR TITLE
Migrated to new csproj format and .NET Standard.

### PR DESCRIPTION
**Pull request by kimbirkelund**
We're in the process of migrating a project of ours to .NET Core and in the process needed a .NET Standard version of the Zoho API.

I've taken the liberty of doing the migration as best I can see. The console app didn't work of the box as far as I can tell, so I didn't do any testing of that, other that it can start.

The migration itself it pretty straight forward for its kind. Csproj files are converted to new format, AssemblyInfo and nuspec stuff is rolled into csproj file or removed.

I'm happy to make further updates if you wish.

### CODE REVIEW

**Comment by jsinh** [comment]
@kimbirkelund - thanks for the efforts. I was wanting to do this change for a while, glad you came up for it. I will give it some time this weekend and update code and NuGet for it, thanks

**Comment by kimbirkelund** [comment]
You're welcome. Looking forward to using it :-)

**Comment by jsinh** [comment]
@kimbirkelund - All good, pushed to NuGet as 0.6.24
https://www.nuget.org/packages/Zoho.Api/
Cheers!!

**Comment by kimbirkelund** [comment]
👍

**Pull request merged**
