### PR TITLE
added missing member on request model for buy one time addon on subscription service

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jsinh** [comment]
Thanks for the contribution.

Are there more updates, pending, can you push them all in same PR so I can merge in one go and check, thanks @kruijs-pixelconcept

**Comment by ghost** [comment]
> 
> 
> Thanks for the contribution.
> 
> Are there more updates, pending, can you push them all in same PR so I can merge in one go and check, thanks @kruijs-pixelconcept

Not at the moment. The second one was because I got a response from ZOHO support far quicker as expected :-)

**Comment by ghost** [comment]
would you please publish version 0.6.23?

**Comment by jsinh** [comment]
@kruijs-pixelconcept - yup done 💃 
Live on NuGet as v0.6.23
https://www.nuget.org/packages/Zoho.Api/

Thanks for the contribution!

**Pull request merged**
